### PR TITLE
Add -x option to use extended 16-color palette

### PR DESCRIPTION
**Pull request by mreinhardt**
Implements #34 

Example using all 16 Monokai colors below:

Example using all 16 Monokai colors

### CODE REVIEW

**Comment by mreinhardt** [comment]
I'm going to rework this a bit to be more bulletproof for all option combinations.

**Comment by mreinhardt** [comment]
Hmm, not sure I need to, any comments/suggestions?

**Comment by dylanaraps** [comment]
LGTM :+1:

**Comment by dylanaraps** [comment]
Thanks for your contribution!

**Pull request merged**
